export const products = [
  {
    id: 1,
    name: "Remera adidas floral",
    price: 3000,
    stock: 5,
    description: "Remera",
    category: "remeras",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698573/fotosCoder-React/remera1_xw4qhx.webp",
  },
  {
    id: 2,
    name: "Pantalon Adidas",
    price: 10000,
    stock: 5,
    description: "Pantalon",
    category: "pantalones",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698572/fotosCoder-React/pantalon1_jmuh2j.webp",
  },
  {
    id: 3,
    name: "Pantalon Puma",
    price: 10000,
    stock: 5,
    description: "Pantalon",
    category: "pantalones",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698572/fotosCoder-React/pantalon2_kqswzk.webp",
  },
  {
    id: 4,
    name: "Remera Adidas Clasica",
    price: 3000,
    stock: 5,
    description: "Remera",
    category: "remeras",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698572/fotosCoder-React/remera2_topsvl.webp",
  },
  {
    id: 5,
    name: "Zapatillas Running",
    price: 16000,
    stock: 5,
    description: "Zapatillas",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698573/fotosCoder-React/zapas1_fqdecc.webp",
  },
  {
    id: 6,
    name: "Buzo Adidas",
    price: 20000,
    stock: 5,
    description: "Buzo",
    category: "buzos",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698573/fotosCoder-React/buzo1_oc6dnf.webp",
  },
  {
    id: 7,
    name: "Buzo Adidas Colores",
    price: 20000,
    stock: 5,
    description: "Buzo",
    category: "buzos",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698573/fotosCoder-React/buzo2_ofnxlg.webp",
  },
  {
    id: 8,
    name: "Ojotas Adidas",
    price: 12000,
    stock: 5,
    description: "Zapatillas",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698573/fotosCoder-React/zapas2_iaqspu.webp",
  },
  {
    id: 9,
    name: "Buzo clasico negro",
    price: 20000,
    stock: 5,
    description: "Buzo",
    category: "buzos",
    img: "https://res.cloudinary.com/dit2o87pv/image/upload/v1670698705/fotosCoder-React/buzo3_bzd8zh.webp",
  },
];
